springbootVersion=3.5.5
springDependencyManagementVersion=1.1.7
javaVersion=21
avroVersion=1.11.3
avroSerializerVersion=7.3.3
jacksonDatabindNullableVersion=0.2.7
swaggerAnnotationsVersion=2.2.36
swaggerParserVersion=2.1.33
avroPluginVersion=1.8.0
jaxbApiVersion=2.3.1
openApiGeneratorVersion=7.15.0
spotlessVersion=6.22.0
sonarqubeVersion=4.4.1.3373
jacocoToolsVersion=0.8.9